version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cleanarchdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
  cleannode:
    container_name: cleannode-api
    image: node:20.10.0
    working_dir: /app
    restart: always
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    ports:
      - '5000:5050'
      - '9222:9222'
    links:
      - mongo

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  clean_node:
    driver: local