version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-clean-arch-ts
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_SITE_BASEURL: /mongoexpress
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - mongo-admin
      - mongo-database

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cleanarchdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mongo-database

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local

networks:
  mongo-database:
  mongo-admin:
